### ISSUE TITLE
[JOSS Review] Repository references in paper

### ISSUE THREAD

**Issue by vissarion** [ttarkowski/quile#5]
There are many references in the JOSS paper the refer to the main branch of the code repository e.g. https://github.com/ttarkowski/quile/blob/main/tutorial/tutorial.txt and https://github.com/ttarkowski/quile/blob/main/README Since the main branch could be changed after the publication of the paper that could potentially create broken links. I think it would be better to create a tagged release of the code in github (the version of that release will be referred in the paper anyways) and create (permanent) links to files of that release.

**Comment by ttarkowski** [comment]
Thank you for your suggestions! I removed links to the software repository and replaced them with text describing locations in software archive. Tagged release v1.0.0 (meant for *software archive* paper metadata) was created and it obtained DOI number [10.5281/zenodo.7603951](https://doi.org/10.5281/zenodo.7603951). Thanks!
